targets:
  $default:
    builders:
      generator|generator:
        enabled: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint

builders:
  generator:
    target: ":"
    import: "package:generator/builder.dart"
    builder_factories: ["generateLogger"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]