name: generator 
description: Generator example.
version: 1.0.0

environment:
  sdk: ">=2.18.0-216 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build:
  analyzer:
  source_gen:

dev_dependencies:
  build_runner: